---
- name: Setup web server and deploy content
  hosts: aws_amazon_linux
  vars:
    git_repo_url: 'https://github.com/Oreire/home_listing.git'
    docker_image: 'nginx:latest'
    container_name: 'portal'
    repo_directory: '/home/ec2-user/home_listings'

  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_directory }}"

    - name: Change directory to Git repository
      command: chdir="{{ repo_directory }}" pwd

    - name: Ensure Docker is installed
      amazon.aws.package:
        name: docker
        state: present

    - name: Add ec2-user to the docker group
      community.general.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Log out ec2-user to apply group changes
      command: pkill -KILL -u ec2-user
      ignore_errors: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker container running NGINX
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "80:80"

    - name: Copy index.html to NGINX container
      community.docker.docker_cp:
        container: "{{ container_name }}"
        src: "{{ repo_directory }}/index.html"
        dest: /usr/share/nginx/html/index.html

    - name: Copy styles.css to NGINX container
      community.docker.docker_cp:
        container: "{{ container_name }}"
        src: "{{ repo_directory }}/styles.css"
        dest: /usr/share/nginx/html/styles.css

    - name: Copy image folder to NGINX container
      community.docker.docker_cp:
        container: "{{ container_name }}"
        src: "{{ repo_directory }}/image"
        dest: /usr/share/nginx/html/image
